const { app, BrowserWindow, WebContentsView, Menu, ipcMain, protocol, session, Tray, dialog, screen, Notification } = require('electron')
const path = require('path')
const fs = require('fs')
const crypto = require('crypto')
const { TabManager, NEW_TAB_URL, attachDevToolsToggle, attachShortcutHandler, resolveInput } = require('./tabManager')
const { SettingsStore } = require('./store')
const { Blocker } = require('./blocker')
const { Pomodoro } = require('./pomodoro')
const { FocusMode } = require('./focusMode')
const { Workspace, MIN_SIDEBAR_WIDTH, MAX_SIDEBAR_WIDTH } = require('./workspace')
const { Profiles } = require('./profiles')
const { UsageStats } = require('./usageStats')
const { History } = require('./history')
const { ActivityLog } = require('./activityLog')
const { AiChat } = require('./aiChat')
const { dotIcon } = require('./trayIcon')
const { DownloadsManager } = require('./downloads')
const { PasswordsManager } = require('./passwords')
const { registerBookmarksIoHandlers } = require('./bookmarksIo')
const { PrivacyManager } = require('./privacy')
const { SearchManager } = require('./search')
const { Theme } = require('./theme')
const { SHORTCUTS } = require('./shortcuts')
const { Onboarding } = require('./onboarding')
const { pathToFileURL } = require('url')

function writeBookmarksJs(list) {
  try {
    const fileContent = `window.BOOKMARKS = ${JSON.stringify(list || [], null, 2)};`
    fs.writeFileSync(path.join(__dirname, '..', 'pages', 'bookmarks.js'), fileContent, 'utf-8')
  } catch (err) {
    console.error("Failed to write bookmarks.js:", err)
  }
}

// Same pattern as writeBookmarksJs: the sandboxed newtab/blocked pages (no
// preload, no IPC by design) read the current theme from a tiny generated
// <script src> file. Written at startup and on every theme change, so a fresh
// page load picks up the right palette with no flash of unthemed content.
// Already-open pages are updated live via executeJavaScript (see pushThemeToTabs).
const BLOCKED_TAB_URL = pathToFileURL(path.join(__dirname, '..', 'pages', 'blocked.html')).toString()
function writeThemeJs(resolved) {
  try {
    const fileContent = `window.FB_THEME = ${JSON.stringify(resolved)};`
    fs.writeFileSync(path.join(__dirname, '..', 'pages', 'theme-state.js'), fileContent, 'utf-8')
  } catch (err) {
    console.error('Failed to write theme-state.js:', err)
  }
}

const CHROME_HEIGHT = 76 // 38px tab strip + 38px toolbar, see src/chrome/chrome.css

// Generated by scripts/build-icon.js (npm run build:icon) — same hand-rolled
// PNG-in-ICO technique as trayIcon.js, not a shipped asset. If this file is
// ever missing, Electron just falls back to its own default icon rather
// than failing to start, so it's safe even before a fresh clone has run
// the build script.
const APP_ICON_PATH = path.join(__dirname, '..', 'chrome', 'assets', 'icon.png')

const TRAY_COLORS = {
  idle: '#6b6d73',
  work: '#d9534f',
  shortBreak: '#5cb85c',
  longBreak: '#5b8def'
}

// Registered before app ready — required for a custom scheme to be usable as
// a real navigation target (see registerUnlockProtocol below). This is how
// the blocked page's friction-override button gets back into the main
// process: tab views deliberately have no preload/IPC since they load
// arbitrary untrusted sites, so a custom protocol stands in for IPC here.
protocol.registerSchemesAsPrivileged([
  { scheme: 'focus-action', privileges: { standard: true, secure: true, corsEnabled: true, supportFetchAPI: true } }
])

// ---- window contexts (multi-window support, Ctrl+N) ----
//
// Every open browser window (the primary one, plus any Ctrl+N secondary
// windows) gets a { win, chromeView, tabManager, isPrimary } entry here.
// IPC handlers that act on "the tab manager" resolve which window sent the
// request via contextForSender(event.sender) instead of assuming a single
// global tabManager — that assumption held fine when only one window could
// ever exist, but silently breaks the first window the moment a second one
// is created (reassigning module-level win/chromeView/tabManager would
// orphan whichever window they used to point at).
//
// Scoped deliberately: secondary windows get tabs/chrome only. The
// workspace sidebar and AI chat sidebar stay exclusive to the primary
// window (win/chromeView/workspaceView/aiSidebarView/tabManager below) —
// giving every window its own independent open folder or chat sidebar
// would mean real product decisions (does opening a folder in one window
// show it in both? a shared chat history or separate ones?) that aren't
// this pass's to make. Settings/Pomodoro/Dashboard are unaffected either
// way — they were already single global utility windows, not per-browser-
// window state.
const windows = []

function primaryContext() {
  return windows.find((ctx) => ctx.isPrimary)
}

// Resolves a window context from *any* webContents that could send a
// request — an IPC message from the chrome view or a primary-only sidebar,
// or a keyboard shortcut from an arbitrary tab (tabs have no preload/IPC, so
// before-input-event is the only signal that can originate there; see
// attachShortcutHandler in tabManager.js). Used for both event.sender (IPC)
// and the webContents passed to keyboard shortcut handlers.
function contextForSender(webContents) {
  const primary = primaryContext()
  if (primary) {
    if (workspaceView && webContents.id === workspaceView.webContents.id) return primary
    if (aiSidebarView && webContents.id === aiSidebarView.webContents.id) return primary
  }
  return windows.find((ctx) => {
    if (ctx.chromeView.webContents.id === webContents.id) return true
    for (const tab of ctx.tabManager.tabs.values()) {
      if (tab.view && tab.view.webContents.id === webContents.id) return true
    }
    return false
  })
}

function broadcastToAllChrome(channel, payload) {
  windows.forEach((ctx) => {
    if (!ctx.chromeView.webContents.isDestroyed()) ctx.chromeView.webContents.send(channel, payload)
  })
}

// Every trusted renderer (chrome for every window, both primary sidebars, and
// each satellite utility window) that should restyle itself when the theme
// changes. Sandboxed tab pages (newtab/blocked) are handled separately via the
// written file + executeJavaScript push, not this list.
function trustedThemeTargets() {
  const targets = []
  windows.forEach((ctx) => targets.push(ctx.chromeView.webContents))
  if (workspaceView) targets.push(workspaceView.webContents)
  if (aiSidebarView) targets.push(aiSidebarView.webContents)
  ;[settingsWin, pomodoroWin, dashboardWin, onboardingWin].forEach((w) => {
    if (w && !w.isDestroyed()) targets.push(w.webContents)
  })
  return targets
}

// Live-update any open newtab/blocked tab. The page defines window.__applyFbTheme
// (see newtab.js / blocked.js); if it isn't defined yet the page is still
// loading and will read the freshly-written theme-state.js on its own.
function pushThemeToTabs(resolved) {
  const js = `window.__applyFbTheme && window.__applyFbTheme(${JSON.stringify(resolved.palette)}, ${JSON.stringify(resolved.mode)});`
  windows.forEach((ctx) => {
    for (const tab of ctx.tabManager.tabs.values()) {
      if (!tab.view || tab.view.webContents.isDestroyed()) continue
      const url = tab.url || ''
      if (url.startsWith(NEW_TAB_URL) || url.startsWith(BLOCKED_TAB_URL)) {
        tab.view.webContents.executeJavaScript(js).catch(() => {})
      }
    }
  })
}

// The single fan-out for a theme change: persist-driven resolved value in,
// every surface updated out.
function applyThemeEverywhere(resolved) {
  writeThemeJs(resolved)
  trustedThemeTargets().forEach((wc) => {
    if (!wc.isDestroyed()) wc.send('theme:changed', resolved)
  })
  pushThemeToTabs(resolved)
}

let win // primary window's BrowserWindow
let chromeView // primary window's chrome WebContentsView
let workspaceView
let aiSidebarView
let tabManager // primary window's TabManager
let settingsWin = null
let pomodoroWin = null
let dashboardWin = null
let onboardingWin = null
let tray = null
let ipcHandlersRegistered = false

// Background macro jobs (see aiChat:runMacro below) — jobId -> { cancelled }.
// Deliberately not persisted: a macro is a live, in-memory run, not
// something that should survive an app restart.
const activeMacroJobs = new Map()

const store = new SettingsStore()
const blocker = new Blocker(store)
const pomodoro = new Pomodoro(store)
const focusMode = new FocusMode(store)
const workspace = new Workspace(store)
const profiles = new Profiles(store)
const usageStats = new UsageStats(store)
const history = new History(store)
const activityLog = new ActivityLog(store)
// getTabManager is a live getter, not the bare `tabManager` variable — it can
// go null/change if the primary window closes and reopens, and AiChat should
// always see the current one rather than a reference captured at construction.
const aiChat = new AiChat({ store, pomodoro, history, activityLog, blocker, getTabManager: () => tabManager, resolveInput })
const downloadsManager = new DownloadsManager(store, broadcastToAllChrome)
const passwordsManager = new PasswordsManager(store)
const privacyManager = new PrivacyManager(store)
const searchManager = new SearchManager(store)
const theme = new Theme(store)
const onboarding = new Onboarding(store)

// Once a minute, while an actual Pomodoro work session is running (not
// paused, not on break), snapshot the primary window's active tab into the
// Activity Log — a lightweight "what was I doing" trail tied to real focus
// sessions rather than all browsing. Skips incognito tabs and blank/new-tab
// pages, same privacy carve-out as History/UsageStats.
setInterval(() => {
  if (!pomodoro.running || pomodoro.phase !== 'work') return
  if (!tabManager) return
  const tab = tabManager.tabs.get(tabManager.activeTabId)
  if (!tab || tab.isIncognito) return
  if (!tab.url || tab.url === NEW_TAB_URL || tab.url.startsWith('file://')) return
  activityLog.record({ url: tab.url, title: tab.title })
}, 60_000)

// Every 5 minutes, while a work session is running AND the user has opted
// into this in Settings → AI Chat, send just THIS session's Activity Log
// (workSessionStartAt onward — never a prior session's, never break-time
// browsing, since the ticker above only ever records during 'work') to the
// AI and let it judge whether things look on-track. The only action it's
// allowed to take is a passive nudge (toast + desktop notification) — it
// cannot block sites, end the session, or otherwise act on its own here.
setInterval(async () => {
  if (!store.get('aiChat').productivityMonitorEnabled) return
  if (!pomodoro.running || pomodoro.phase !== 'work' || !workSessionStartAt) return

  const entries = activityLog.getRecent(500).filter((e) => e.timestamp >= workSessionStartAt)
  if (!entries.length) return

  const result = await aiChat.checkProductivity({ entries })
  if (result.checked && result.offTrack && result.message) {
    chromeView?.webContents.send('toast:show', `🎯 ${result.message}`)
    if (Notification.isSupported()) {
      // timeoutType: 'never' — the default toast duration is too short to
      // actually read a 1-2 sentence nudge; this keeps it up until the user
      // dismisses it themselves (Windows/Linux; macOS has no equivalent and
      // just falls back to its own default, harmlessly ignoring the option).
      new Notification({ title: 'Focus check-in', body: result.message, timeoutType: 'never' }).show()
    }
    const nudge = { message: result.message, timestamp: Date.now() }
    store.update('productivityNudge', nudge)
    dashboardWin?.webContents.send('productivityNudge:state', nudge)
  }
}, 5 * 60_000)

// Snapshot of blocker/focusMode.enabled taken right before a Pomodoro work
// session forces them on, so breaks restore whatever the user actually had
// set rather than always flipping back to off (Milestone 5 integration).
let autoFocusSnapshot = null
function applyAutoFocus() {
  if (autoFocusSnapshot) return
  autoFocusSnapshot = { blocker: blocker.state.enabled, focusMode: focusMode.state.enabled }
  blocker.setEnabled(true)
  focusMode.setEnabled(true)
}
function revertAutoFocus() {
  if (!autoFocusSnapshot) return
  blocker.setEnabled(autoFocusSnapshot.blocker)
  focusMode.setEnabled(autoFocusSnapshot.focusMode)
  autoFocusSnapshot = null
}

// Timestamp the current Pomodoro work phase began, or null when not in one
// — lets the productivity monitor (below) scope the Activity Log to just
// this session instead of the whole stored history, and skip entirely
// across a break (set null on phase end, so a stale timestamp from a prior
// session can never leak in).
let workSessionStartAt = null

function createBrowserWindow(isPrimary, isIncognito = false) {
  const sessionInstance = isIncognito
    ? session.fromPartition('incognito_' + Date.now())
    : session.defaultSession

  // Ensure blocker and privacy rules are installed on the incognito session
  if (isIncognito) {
    blocker.install(sessionInstance)
    privacyManager.registerSession(sessionInstance)
    downloadsManager.registerSession(sessionInstance)
  }

  const localWin = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 760,
    minHeight: 480,
    backgroundColor: '#1e1f22',
    title: isIncognito ? 'Focus Browser (Incognito)' : 'Focus Browser',
    icon: APP_ICON_PATH,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      session: sessionInstance
    }
  })

  // Native title bar stays (simplest/most reliable for v1 on Windows); the
  // default File/Edit/View menu is stripped since our own toolbar replaces
  // it. Set once — Menu.setApplicationMenu applies to every window Electron
  // creates afterward, primary or secondary, so it doesn't need repeating.
  if (isPrimary) {
    if (process.platform === 'darwin') {
      const template = [
        {
          label: app.name,
          submenu: [
            { role: 'about' },
            { type: 'separator' },
            { role: 'services' },
            { type: 'separator' },
            { role: 'hide' },
            { role: 'hideOthers' },
            { role: 'unhide' },
            { type: 'separator' },
            { role: 'quit' }
          ]
        },
        {
          label: 'File',
          submenu: [
            { role: 'close' }
          ]
        },
        {
          label: 'Edit',
          submenu: [
            { role: 'undo' },
            { role: 'redo' },
            { type: 'separator' },
            { role: 'cut' },
            { role: 'copy' },
            { role: 'paste' },
            { role: 'pasteAndMatchStyle' },
            { role: 'delete' },
            { role: 'selectAll' },
            { type: 'separator' },
            {
              label: 'Speech',
              submenu: [
                { role: 'startSpeaking' },
                { role: 'stopSpeaking' }
              ]
            }
          ]
        },
        {
          label: 'View',
          submenu: [
            { role: 'reload' },
            { role: 'forceReload' },
            { role: 'toggleDevTools' },
            { type: 'separator' },
            { role: 'resetZoom' },
            { role: 'zoomIn' },
            { role: 'zoomOut' },
            { type: 'separator' },
            { role: 'togglefullscreen' }
          ]
        },
        {
          label: 'Window',
          submenu: [
            { role: 'minimize' },
            { role: 'zoom' },
            { type: 'separator' },
            { role: 'front' },
            { type: 'separator' },
            { role: 'window' }
          ]
        }
      ]
      const menu = Menu.buildFromTemplate(template)
      Menu.setApplicationMenu(menu)
    } else {
      Menu.setApplicationMenu(null)
    }
  }
  if (isPrimary) workspace.setWindow(localWin)

  const localChromeView = new WebContentsView({
    webPreferences: {
      preload: path.join(__dirname, '..', 'preload', 'chrome-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      session: sessionInstance
    }
  })
  localWin.contentView.addChildView(localChromeView)
  attachDevToolsToggle(localChromeView.webContents)
  attachShortcutHandler(localChromeView.webContents, handleGlobalShortcut)
  localChromeView.webContents.loadFile(path.join(__dirname, '..', 'chrome', 'index.html'))

  // Lazy + memoized: only actually created the first time this (otherwise
  // normal) window opens an individual incognito tab, so ordinary windows
  // that never touch the feature don't pay for an unused session/partition.
  let perWindowIncognitoSession = null
  const createIncognitoSession = () => {
    if (!perWindowIncognitoSession) {
      perWindowIncognitoSession = session.fromPartition('incognito-tab_' + Date.now() + '_' + Math.random().toString(36).slice(2))
      blocker.install(perWindowIncognitoSession)
      privacyManager.registerSession(perWindowIncognitoSession)
      downloadsManager.registerSession(perWindowIncognitoSession)
    }
    return perWindowIncognitoSession
  }

  const localTabManager = new TabManager(localWin, localChromeView, CHROME_HEIGHT, {
    focusMode,
    store,
    history,
    onToast: (message) => localChromeView?.webContents.send('toast:show', message),
    onActiveUrlChange: (url) => {
      if (!isIncognito) usageStats.startTracking(url)
    },
    onKeyboardShortcut: handleGlobalShortcut,
    onTabDomReady: (wc, url) => passwordsManager.autofillTab(wc, url),
    isIncognito,
    session: sessionInstance,
    createIncognitoSession
  })

  const ctx = { win: localWin, chromeView: localChromeView, tabManager: localTabManager, isPrimary }
  windows.push(ctx)

  if (isPrimary) {
    win = localWin
    chromeView = localChromeView
    tabManager = localTabManager

    workspaceView = new WebContentsView({
      webPreferences: {
        preload: path.join(__dirname, '..', 'workspace', 'workspace-preload.js'),
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true
      }
    })
    localWin.contentView.addChildView(workspaceView)
    attachDevToolsToggle(workspaceView.webContents)
    attachShortcutHandler(workspaceView.webContents, handleGlobalShortcut)
    workspaceView.webContents.loadFile(path.join(__dirname, '..', 'workspace', 'index.html'))
    localTabManager.attachSidebar(workspaceView)
    localTabManager.setSidebarWidth(workspace.state.sidebarWidth) // restore last session's width
    localTabManager.setSidebarVisible(workspace.state.sidebarVisible) // restore last session's toggle state

    aiSidebarView = new WebContentsView({
      webPreferences: {
        preload: path.join(__dirname, '..', 'aiChat', 'aiChat-preload.js'),
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true
      }
    })
    localWin.contentView.addChildView(aiSidebarView)
    attachDevToolsToggle(aiSidebarView.webContents)
    attachShortcutHandler(aiSidebarView.webContents, handleGlobalShortcut)
    aiSidebarView.webContents.loadFile(path.join(__dirname, '..', 'aiChat', 'index.html'))
    localTabManager.attachRightSidebar(aiSidebarView)
    localTabManager.setRightSidebarWidth(store.get('aiChat').sidebarWidth)
    localTabManager.setRightSidebarVisible(store.get('aiChat').sidebarVisible)
  }

  // Wait for the chrome UI's JS to be ready to receive state before creating
  // the first tab, so the initial broadcastState() isn't sent into the void.
  localChromeView.webContents.once('did-finish-load', () => {
    localChromeView.webContents.send('chrome:setIncognito', isIncognito)
    localTabManager.createTab(NEW_TAB_URL)
  })

  if (!ipcHandlersRegistered) {
    registerIpcHandlers()
    ipcHandlersRegistered = true
  }

  if (isPrimary) {
    // Safety net: if the window loses focus mid-drag (alt-tab, a native
    // dialog stealing focus, whatever), the drag has no way to end itself
    // normally, so force it to stop rather than leave the interval running.
    localWin.on('blur', () => stopSidebarResize())
  }

  // UsageStats tracks attention, not just "a tab is open" — pause the clock
  // the moment the focused window loses focus, resume on whatever tab is
  // active in whichever window gains it. One shared tracker across all
  // windows, same as a single global timer would only ever have one "now."
  localWin.on('blur', () => usageStats.stopTracking())
  localWin.on('focus', () => {
    const url = localTabManager.getActiveUrl()
    if (url && !localTabManager.isActiveTabIncognito()) usageStats.startTracking(url)
  })

  localWin.on('closed', () => {
    const idx = windows.indexOf(ctx)
    if (idx !== -1) windows.splice(idx, 1)
    localTabManager.destroy()
    if (isPrimary) win = null
  })

  // See TabManager.forceRepaint() — Windows sometimes leaves every child
  // WebContentsView showing a flat grey (the BrowserWindow's own
  // backgroundColor) after minimize → restore until something forces a
  // repaint. This also nudges the actual OS window's own bounds (not just
  // its children's) since some cases only repaint once the top-level window
  // itself gets a real resize, not just the views living inside it.
  localWin.on('restore', () => {
    localTabManager.forceRepaint()
    // Skip the top-level nudge if maximized — setBounds() on a maximized
    // window can pop it out of the maximized state, which would be a worse
    // visible glitch than the one being worked around here.
    if (localWin.isMaximized()) return
    const bounds = localWin.getBounds()
    localWin.setBounds({ ...bounds, height: bounds.height + 1 })
    setTimeout(() => {
      if (!localWin.isDestroyed()) localWin.setBounds(bounds)
    }, 30)
  })

  return ctx
}

function createWindow() {
  createBrowserWindow(windows.length === 0)
}

function createSecondaryWindow() {
  createBrowserWindow(false)
}

function createIncognitoWindow() {
  createBrowserWindow(false, true)
}

function zoomActiveTab(webContents, direction) {
  const ctx = contextForSender(webContents)
  if (!ctx) return
  const activeId = ctx.tabManager.activeTabId
  const tab = ctx.tabManager.tabs.get(activeId)
  if (!tab || !tab.view) return
  const wc = tab.view.webContents
  
  let factor = wc.getZoomFactor()
  if (direction === 1) {
    factor = Math.min(3.0, factor + 0.1)
  } else if (direction === -1) {
    factor = Math.max(0.3, factor - 0.1)
  } else {
    factor = 1.0
  }
  
  wc.setZoomFactor(factor)
  
  try {
    const url = new URL(tab.url)
    const host = url.hostname.toLowerCase()
    const zoomSettings = store.get('zoomSettings') || { hosts: {} }
    if (!zoomSettings.hosts) zoomSettings.hosts = {}
    
    if (factor === 1.0) {
      delete zoomSettings.hosts[host]
    } else {
      zoomSettings.hosts[host] = factor
    }
    
    store.update('zoomSettings', { hosts: zoomSettings.hosts })
    ctx.chromeView.webContents.send('tab:zoomChanged', { tabId: tab.id, zoomFactor: factor })
  } catch (err) {
    // ignore local files
  }
}

// ---- keyboard shortcuts ----
//
// Attached via before-input-event to every webContents the browser creates
// (chrome, both primary-only sidebars, and every tab in every window — see
// attachShortcutHandler in tabManager.js) rather than Electron menu
// accelerators, since the app menu is stripped entirely
// (Menu.setApplicationMenu(null)). Returning true tells the caller to
// preventDefault, which matters for things like Ctrl+W: without it, the
// keystroke would also reach whatever page or input field has focus.
function handleGlobalShortcut(input, webContents) {
  const isCmdOrCtrl = process.platform === 'darwin' ? input.meta : input.control
  const isOtherModifier = process.platform === 'darwin' ? input.control || input.alt : input.meta || input.alt
  if (input.type !== 'keyDown' || !isCmdOrCtrl || isOtherModifier) return false
  const key = input.key.toLowerCase()

  if (key === 'n' && !input.shift) {
    createSecondaryWindow()
    return true
  }

  if (key === 'n' && input.shift) {
    createIncognitoWindow()
    return true
  }

  if (key === '=' || key === '+') {
    zoomActiveTab(webContents, 1)
    return true
  }
  if (key === '-') {
    zoomActiveTab(webContents, -1)
    return true
  }
  if (key === '0') {
    zoomActiveTab(webContents, 0)
    return true
  }
  if (key === 'p') {
    const ctx = contextForSender(webContents)
    if (ctx) {
      const activeId = ctx.tabManager.activeTabId
      const tab = ctx.tabManager.tabs.get(activeId)
      if (tab && tab.view) {
        tab.view.webContents.print({ silent: false, printBackground: true })
      }
    }
    return true
  }
  if (key === 'f') {
    const ctx = contextForSender(webContents)
    if (ctx) {
      ctx.chromeView.webContents.send('tab:findInPageToggle')
    }
    return true
  }

  const ctx = contextForSender(webContents)
  if (!ctx) return false
  const tm = ctx.tabManager

  if (key === 't' && !input.shift) {
    tm.createTab()
    return true
  }
  if (key === 't' && input.shift) {
    tm.reopenClosedTab()
    return true
  }
  if (key === 'w' && !input.shift) {
    if (tm.activeTabId) tm.closeTab(tm.activeTabId)
    return true
  }
  if (key === 'tab') {
    tm.switchToNextTab()
    return true
  }
  if (/^[1-8]$/.test(key)) {
    tm.switchToTabIndex(Number(key) - 1)
    return true
  }
  return false
}

// ---- workspace sidebar drag-to-resize ----
//
// Tracking uses screen.getCursorScreenPoint() polled from the main process,
// not renderer mousemove — a renderer's DOM events stop once the cursor
// leaves that WebContentsView's bounds, and a resize drag needs to keep
// tracking even as the boundary itself moves under the cursor. Polling the
// OS cursor position directly sidesteps that entirely: it doesn't care
// which view (if any) the cursor is currently hit-testing into. Primary-
// window-only, same as the workspace sidebar itself.
//
// The corresponding mouseup listener still lives in the renderer (see
// workspace.js) and relies on the view's bounds being kept just past the
// cursor on every tick (RESIZE_EDGE_BUFFER) so that release reliably lands
// inside the workspace view's hit region rather than the tab view beyond it.
const RESIZE_EDGE_BUFFER = 8
let resizeInterval = null
let resizeTimeout = null

function startSidebarResize() {
  stopSidebarResize()
  if (!win || !tabManager?.sidebarVisible) return
  resizeInterval = setInterval(() => {
    if (!win) return
    const contentBounds = win.getContentBounds()
    const cursor = screen.getCursorScreenPoint()
    const relativeX = cursor.x - contentBounds.x + RESIZE_EDGE_BUFFER
    const clamped = Math.min(MAX_SIDEBAR_WIDTH, Math.max(MIN_SIDEBAR_WIDTH, relativeX))
    tabManager.setSidebarWidth(clamped) // live visual only — no disk write per tick
  }, 16)
  // A drag that never gets a clean end signal (cursor released somewhere
  // this app has no listener, e.g. off-screen) shouldn't spin forever.
  resizeTimeout = setTimeout(stopSidebarResize, 15000)
}

function stopSidebarResize() {
  if (resizeTimeout) {
    clearTimeout(resizeTimeout)
    resizeTimeout = null
  }
  if (!resizeInterval) return
  clearInterval(resizeInterval)
  resizeInterval = null
  if (tabManager) workspace.setSidebarWidth(tabManager.sidebarWidth) // persist the final width once
}

function registerUnlockProtocol() {
  session.defaultSession.protocol.handle('focus-action', async (request) => {
    const url = new URL(request.url)
    if (url.hostname === 'unlock') {
      const host = url.searchParams.get('host')
      const target = url.searchParams.get('target')
      const minutes = Number(url.searchParams.get('minutes')) || 10
      console.log('=== UNLOCK PROTOCOL CALLED ===', { host, target, minutes })
      if (host && target) blocker.temporarilyUnlock(host, minutes)
      console.log('=== CURRENT ACTIVE UNLOCKS ===', Array.from(blocker.temporaryUnlocks.entries()))
      return new Response(null, { status: 302, headers: { Location: target || NEW_TAB_URL } })
    }

    if (url.hostname === 'evaluate') {
      const host = url.searchParams.get('host') || ''
      const justification = url.searchParams.get('justification') || ''
      try {
        const result = await aiChat.evaluateJustification({ host, justification })
        return new Response(JSON.stringify(result), {
          headers: { 
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'
          }
        })
      } catch (err) {
        return new Response(JSON.stringify({ approved: true, reason: 'AI Gatekeeper bypass: ' + err.message }), {
          headers: { 
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'
          }
        })
      }
    }

    return new Response('Not found', { status: 404 })
  })
}

// ---- settings window ----

function openSettingsWindow() {
  if (settingsWin && !settingsWin.isDestroyed()) {
    settingsWin.show()
    settingsWin.focus()
    return
  }
  settingsWin = new BrowserWindow({
    width: 720,
    height: 580,
    title: 'Settings',
    backgroundColor: '#1e1f22',
    icon: APP_ICON_PATH,
    parent: win,
    webPreferences: {
      preload: path.join(__dirname, '..', 'settings', 'settings-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  })
  settingsWin.setMenu(null)
  settingsWin.loadFile(path.join(__dirname, '..', 'settings', 'index.html'))
  settingsWin.on('closed', () => { settingsWin = null })
}

// ---- pomodoro mini window ----

function togglePomodoroWindow(forceShow) {
  if (pomodoroWin && !pomodoroWin.isDestroyed()) {
    if (forceShow || !pomodoroWin.isVisible()) {
      pomodoroWin.show()
      pomodoroWin.focus()
    } else {
      pomodoroWin.hide()
    }
    return
  }
  pomodoroWin = new BrowserWindow({
    width: 380,
    height: 380,
    resizable: false,
    minimizable: false,
    maximizable: false,
    title: 'Focus Timer',
    backgroundColor: '#1e1f22',
    icon: APP_ICON_PATH,
    webPreferences: {
      preload: path.join(__dirname, '..', 'pomodoro', 'pomodoro-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  })
  pomodoroWin.setMenu(null)
  pomodoroWin.loadFile(path.join(__dirname, '..', 'pomodoro', 'index.html'))
  // Hide rather than destroy on close so the timer keeps running in the
  // background and reopening doesn't flash a brand-new window — this is
  // meant to be a "glance at it" panel, not a one-shot dialog.
  pomodoroWin.on('close', (e) => {
    if (!app.isQuiting) {
      e.preventDefault()
      pomodoroWin.hide()
    }
  })
}

// ---- usage dashboard window ----

function openDashboardWindow() {
  if (dashboardWin && !dashboardWin.isDestroyed()) {
    dashboardWin.show()
    dashboardWin.focus()
    return
  }
  dashboardWin = new BrowserWindow({
    width: 480,
    height: 600,
    title: 'Usage Dashboard',
    backgroundColor: '#1e1f22',
    icon: APP_ICON_PATH,
    parent: win,
    webPreferences: {
      preload: path.join(__dirname, '..', 'dashboard', 'dashboard-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  })
  dashboardWin.setMenu(null)
  dashboardWin.loadFile(path.join(__dirname, '..', 'dashboard', 'index.html'))
  dashboardWin.on('closed', () => { dashboardWin = null })
}

// ---- onboarding modal window ----

function openOnboardingWindow(force) {
  // Reuse if already open.
  if (onboardingWin && !onboardingWin.isDestroyed()) {
    onboardingWin.show()
    onboardingWin.focus()
    return
  }
  // Don't auto-show if already completed (unless forced from Settings).
  if (!force && onboarding.isCompleted()) return

  onboardingWin = new BrowserWindow({
    width: 560,
    height: 420,
    resizable: false,
    minimizable: false,
    maximizable: false,
    title: 'Welcome to Focus Browser',
    backgroundColor: '#211d1a',
    icon: APP_ICON_PATH,
    parent: win,
    modal: true,
    webPreferences: {
      preload: path.join(__dirname, '..', 'onboarding', 'onboarding-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  })
  onboardingWin.setMenu(null)
  onboardingWin.loadFile(path.join(__dirname, '..', 'onboarding', 'index.html'))
  onboardingWin.on('closed', () => { onboardingWin = null })
}

// ---- tray ----

function formatTime(ms) {
  const total = Math.max(0, Math.round(ms / 1000))
  const m = Math.floor(total / 60)
  const s = total % 60
  return `${m}:${String(s).padStart(2, '0')}`
}

const PHASE_NAMES = { work: 'Work', shortBreak: 'Short break', longBreak: 'Long break' }

function setupTray() {
  tray = new Tray(dotIcon(TRAY_COLORS.idle))
  tray.on('click', () => togglePomodoroWindow(true))
  updateTray()
}

function updateTray() {
  if (!tray || tray.isDestroyed()) return
  const s = pomodoro.getState()
  const label = `${PHASE_NAMES[s.phase]} — ${formatTime(s.remainingMs)}`

  tray.setToolTip(`Focus Browser — ${label}`)
  tray.setImage(dotIcon(s.running ? TRAY_COLORS[s.phase] : TRAY_COLORS.idle))
  tray.setContextMenu(Menu.buildFromTemplate([
    { label, enabled: false },
    { type: 'separator' },
    s.running
      ? { label: 'Pause', click: () => pomodoro.pause() }
      : { label: 'Start', click: () => pomodoro.start() },
    { label: 'Reset', click: () => pomodoro.reset() },
    { label: 'Skip', click: () => pomodoro.skip() },
    { type: 'separator' },
    { label: 'Open timer', click: () => togglePomodoroWindow(true) },
    { label: 'Settings…', click: () => openSettingsWindow() },
    { type: 'separator' },
    { label: 'Quit Focus Browser', click: () => app.quit() }
  ]))
}

// ---- native popup menus ----
//
// The chrome UI's tab strip/toolbar live in a WebContentsView that's only
// CHROME_HEIGHT (76px) tall — its content is physically clipped to that
// rectangle, `position: fixed` and z-index included, the same way an
// iframe's content can't render outside its box. A custom HTML dropdown
// taller than that (a launcher list, a multi-item context menu) renders but
// is invisible past the 76px line. Native menus aren't web content, so
// they aren't bound by any view's rectangle — that's why both of these use
// Menu.popup() instead of an in-page element. Both take the resolved window
// context explicitly (rather than reaching for the bare primary tabManager)
// so they act on whichever window actually sent the request.

function showTabContextMenu(ctx, tabId, x, y) {
  const state = ctx.tabManager.getState()
  const tab = state.tabs.find((t) => t.id === tabId)
  if (!tab) return

  const template = [
    {
      label: 'New group from tab',
      click: () => {
        const groupId = ctx.tabManager.createGroup()
        ctx.tabManager.addTabToGroup(tabId, groupId)
      }
    }
  ]

  if (tab.groupId) {
    template.push({ label: 'Remove from group', click: () => ctx.tabManager.removeTabFromGroup(tabId) })
    template.push({ label: 'Close group', click: () => ctx.tabManager.closeGroup(tab.groupId) })
  } else if (state.groups.length) {
    state.groups.forEach((g) => {
      template.push({ label: `Add to "${g.name}"`, click: () => ctx.tabManager.addTabToGroup(tabId, g.id) })
    })
  }

  if (tabId !== ctx.tabManager.activeTabId && !tab.frozen) {
    template.push({ type: 'separator' })
    template.push({ label: 'Freeze tab (free its memory)', click: () => ctx.tabManager.freezeTab(tabId) })
  }

  template.push({ type: 'separator' })
  template.push({
    label: tab.isMuted ? 'Unmute tab' : 'Mute tab',
    click: () => ctx.tabManager.toggleMute(tabId)
  })
  template.push({
    label: 'Print...',
    click: () => {
      const t = ctx.tabManager.tabs.get(tabId)
      if (t && t.view) t.view.webContents.print({ silent: false, printBackground: true })
    }
  })

  template.push({ type: 'separator' })
  template.push({ label: 'Close tab', click: () => ctx.tabManager.closeTab(tabId) })

  Menu.buildFromTemplate(template).popup({ window: ctx.win, x: Math.round(x), y: Math.round(y) })
}

function showNewTabContextMenu(ctx, x, y) {
  const template = [
    { label: 'New Tab', click: () => ctx.tabManager.createTab(NEW_TAB_URL) },
    { label: 'New Incognito Tab', click: () => ctx.tabManager.createTab(NEW_TAB_URL, { incognito: true }) }
  ]
  Menu.buildFromTemplate(template).popup({ window: ctx.win, x: Math.round(x), y: Math.round(y) })
}

function showLauncherMenu(ctx, x, y) {
  const list = profiles.state.list
  const template = []

  if (!list.length) {
    template.push({ label: 'No profiles yet', enabled: false })
  } else {
    list.forEach((profile) => {
      template.push({
        label: profile.name,
        click: () => {
          profiles.launchProfile(profile.id, { onOpenUrl: (url) => ctx.tabManager.createTab(resolveInput(url)) })
        }
      })
    })
  }

  template.push({ type: 'separator' })
  template.push({ label: 'Manage profiles…', click: () => openSettingsWindow() })

  Menu.buildFromTemplate(template).popup({ window: ctx.win, x: Math.round(x), y: Math.round(y) })
}

// ---- ipc ----

function registerIpcHandlers() {
  ipcMain.on('tab:new', (e, url) => {
    let ctx = contextForSender(e.sender)
    if (!ctx) ctx = primaryContext()
    ctx?.tabManager.createTab(url)
  })
  ipcMain.on('tab:newIncognito', (e) => {
    let ctx = contextForSender(e.sender)
    if (!ctx) ctx = primaryContext()
    ctx?.tabManager.createTab(NEW_TAB_URL, { incognito: true })
  })
  ipcMain.on('tab:showNewTabContextMenu', (e, { x, y }) => {
    const ctx = contextForSender(e.sender)
    if (ctx) showNewTabContextMenu(ctx, x, y)
  })
  ipcMain.on('tab:close', (e, id) => contextForSender(e.sender)?.tabManager.closeTab(id))
  ipcMain.on('tab:switch', (e, id) => contextForSender(e.sender)?.tabManager.switchTab(id))
  ipcMain.on('tab:navigate', (e, { id, input }) => contextForSender(e.sender)?.tabManager.navigate(id, input))
  ipcMain.on('tab:back', (e, id) => contextForSender(e.sender)?.tabManager.goBack(id))
  ipcMain.on('tab:forward', (e, id) => contextForSender(e.sender)?.tabManager.goForward(id))
  ipcMain.on('tab:reload', (e, id) => contextForSender(e.sender)?.tabManager.reload(id))
  ipcMain.on('tab:toggleReader', (e, id) => contextForSender(e.sender)?.tabManager.toggleReaderMode(id))
  ipcMain.on('tab:toggleMute', (e, id) => contextForSender(e.sender)?.tabManager.toggleMute(id))
  ipcMain.on('tab:findInPage', (e, { id, text, options }) => {
    const ctx = contextForSender(e.sender)
    if (!ctx) return
    const tab = ctx.tabManager.tabs.get(id)
    if (tab && tab.view) {
      tab.view.webContents.findInPage(text, options)
    }
  })
  ipcMain.on('tab:stopFindInPage', (e, { id, action }) => {
    const ctx = contextForSender(e.sender)
    if (!ctx) return
    const tab = ctx.tabManager.tabs.get(id)
    if (tab && tab.view) {
      tab.view.webContents.stopFindInPage(action)
    }
  })
  ipcMain.on('tab:resetZoom', (e, id) => {
    const ctx = contextForSender(e.sender)
    if (!ctx) return
    const tab = ctx.tabManager.tabs.get(id)
    if (tab && tab.view) {
      tab.view.webContents.setZoomFactor(1.0)
      try {
        const host = new URL(tab.url).hostname.toLowerCase()
        const zoomSettings = store.get('zoomSettings') || { hosts: {} }
        if (zoomSettings.hosts) {
          delete zoomSettings.hosts[host]
          store.update('zoomSettings', { hosts: zoomSettings.hosts })
        }
      } catch {}
      ctx.chromeView.webContents.send('tab:zoomChanged', { tabId: id, zoomFactor: 1.0 })
    }
  })

  ipcMain.handle('group:create', (e) => contextForSender(e.sender)?.tabManager.createGroup())
  ipcMain.on('group:addTab', (e, { tabId, groupId }) => contextForSender(e.sender)?.tabManager.addTabToGroup(tabId, groupId))
  ipcMain.on('group:removeTab', (e, tabId) => contextForSender(e.sender)?.tabManager.removeTabFromGroup(tabId))
  ipcMain.on('group:close', (e, groupId) => contextForSender(e.sender)?.tabManager.closeGroup(groupId))

  ipcMain.handle('tabs:getState', (e) => contextForSender(e.sender)?.tabManager.getState())

  ipcMain.handle('blocker:getState', () => blocker.state)
  ipcMain.on('blocker:setEnabled', (_e, enabled) => blocker.setEnabled(enabled))
  ipcMain.on('blocker:addBlock', (_e, pattern) => blocker.addBlock(pattern))
  ipcMain.on('blocker:removeBlock', (_e, pattern) => blocker.removeBlock(pattern))
  ipcMain.on('blocker:addAllow', (_e, pattern) => blocker.addAllow(pattern))
  ipcMain.on('blocker:removeAllow', (_e, pattern) => blocker.removeAllow(pattern))

  ipcMain.handle('pomodoro:getState', () => pomodoro.getState())
  ipcMain.on('pomodoro:start', () => pomodoro.start())
  ipcMain.on('pomodoro:pause', () => pomodoro.pause())
  ipcMain.on('pomodoro:reset', () => pomodoro.reset())
  ipcMain.on('pomodoro:skip', () => pomodoro.skip())
  ipcMain.on('pomodoro:updateSettings', (_e, patch) => pomodoro.updateSettings(patch))
  ipcMain.on('pomodoro:setMuted', (_e, muted) => pomodoro.setMuted(muted))
  ipcMain.on('pomodoro:adjustTime', (_e, minutes) => {
    const n = Number(minutes)
    if (Number.isFinite(n) && n !== 0) pomodoro.adjustTime(n * 60_000)
  })

  ipcMain.on('settings:open', () => openSettingsWindow())
  ipcMain.on('pomodoro:openPanel', () => togglePomodoroWindow(true))

  // theme:getResolved — what trusted renderers apply (mode already light/dark).
  // theme:getRaw — the stored preference (mode may be 'system'), for the
  // Appearance UI's toggle state. theme:set persists + fans out to everything.
  ipcMain.handle('theme:getResolved', () => theme.getResolved())
  ipcMain.handle('theme:getRaw', () => theme.getRaw())
  ipcMain.handle('theme:set', (_e, pref) => {
    const resolved = theme.set(pref || {})
    // Echo the raw preference back to the Settings window so its toggle
    // reflects exactly what was stored (e.g. 'system'), not the resolved value.
    settingsWin?.webContents.send('theme:rawChanged', theme.getRaw())
    return resolved
  })

  ipcMain.handle('shortcuts:getList', () => {
    if (process.platform === 'darwin') {
      return SHORTCUTS.map(group => ({
        ...group,
        items: group.items.map(item => ({
          ...item,
          keys: item.keys.map(k => k === 'Ctrl' ? 'Cmd' : k)
        }))
      }))
    }
    return SHORTCUTS
  })

  ipcMain.handle('settings:getMeta', () => store.get('settings'))
  ipcMain.on('settings:setLastCategory', (_e, category) => {
    if (typeof category === 'string') store.update('settings', { lastOpenCategory: category })
  })

  ipcMain.on('onboarding:show', () => openOnboardingWindow(true))

  // Both 'completed' and 'skipped' mark onboarding done — zero telemetry,
  // no distinction stored. Close the window in either case.
  ipcMain.on('onboarding:dismiss', (_e, _reason) => {
    onboarding.markCompleted()
    if (onboardingWin && !onboardingWin.isDestroyed()) {
      onboardingWin.close()
    }
  })

  // Clear Browsing Data (Privacy → Clear Browsing Data): history + cookies/
  // site data + cache, all local, all at once. Returns a small summary.
  ipcMain.handle('privacy:clearBrowsingData', async () => {
    const result = { history: false, storage: false, cache: false }
    try { history.clearAll(); result.history = true } catch {}
    try { await session.defaultSession.clearStorageData(); result.storage = true } catch {}
    try { await session.defaultSession.clearCache(); result.cache = true } catch {}
    // Refresh any views showing this data.
    windows.forEach((ctx) => ctx.tabManager.broadcastState())
    settingsWin?.webContents.send('privacy:state', store.get('permissions'))
    return result
  })

  ipcMain.handle('focusMode:getState', () => focusMode.state)
  ipcMain.on('focusMode:setEnabled', (_e, enabled) => focusMode.setEnabled(enabled))
  ipcMain.on('focusMode:setTabLimit', (_e, limit) => focusMode.setTabLimit(limit))

  ipcMain.handle('workspace:pickFolder', () => workspace.pickFolder())
  ipcMain.handle('workspace:getState', () => workspace.state)
  ipcMain.handle('workspace:readDir', (_e, dirPath) => workspace.readDir(dirPath))
  ipcMain.handle('workspace:readFile', (_e, filePath) => workspace.readFile(filePath))
  ipcMain.handle('workspace:writeFile', (_e, filePath, content) => workspace.writeFile(filePath, content))
  ipcMain.on('workspace:toggleSidebar', () => {
    const next = !workspace.state.sidebarVisible
    workspace.setSidebarVisible(next)
    tabManager.setSidebarVisible(next)
  })
  ipcMain.on('workspace:setSidebarWidth', (_e, px) => {
    const clamped = workspace.setSidebarWidth(px)
    tabManager.setSidebarWidth(clamped)
  })
  ipcMain.on('workspace:setTreeCollapsed', (_e, collapsed) => workspace.setTreeCollapsed(collapsed))
  ipcMain.on('workspace:resizeStart', () => startSidebarResize())
  ipcMain.on('workspace:resizeEnd', () => stopSidebarResize())

  ipcMain.handle('profiles:getState', () => profiles.state)
  ipcMain.on('profiles:add', (_e, profile) => profiles.addProfile(profile))
  ipcMain.on('profiles:update', (_e, { id, patch }) => profiles.updateProfile(id, patch))
  ipcMain.on('profiles:remove', (_e, id) => profiles.removeProfile(id))
  ipcMain.on('profiles:launch', (e, id) => {
    const ctx = contextForSender(e.sender)
    if (!ctx) return
    profiles.launchProfile(id, { onOpenUrl: (url) => ctx.tabManager.createTab(resolveInput(url)) })
  })

  ipcMain.on('tab:showContextMenu', (e, { tabId, x, y }) => {
    const ctx = contextForSender(e.sender)
    if (ctx) showTabContextMenu(ctx, tabId, x, y)
  })
  ipcMain.on('launcher:showMenu', (e, { x, y }) => {
    const ctx = contextForSender(e.sender)
    if (ctx) showLauncherMenu(ctx, x, y)
  })

  ipcMain.handle('profiles:pickCwd', async () => {
    const result = await dialog.showOpenDialog(settingsWin, { properties: ['openDirectory'] })
    return result.canceled ? null : result.filePaths[0]
  })

  ipcMain.handle('tabFreezing:getState', () => store.get('tabFreezing'))
  ipcMain.on('tabFreezing:setEnabled', (_e, enabled) => {
    store.update('tabFreezing', { enabled: !!enabled })
    settingsWin?.webContents.send('tabFreezing:state', store.get('tabFreezing'))
  })
  ipcMain.on('tabFreezing:setFreezeAfterMin', (_e, minutes) => {
    const n = Math.max(1, Math.floor(Number(minutes)) || 10)
    store.update('tabFreezing', { freezeAfterMin: n })
    settingsWin?.webContents.send('tabFreezing:state', store.get('tabFreezing'))
  })

  ipcMain.on('dashboard:open', () => openDashboardWindow())
  ipcMain.handle('usageStats:getToday', () => usageStats.getDaySummary())
  ipcMain.handle('usageStats:getWeek', () => usageStats.getRecentDays(7))
  ipcMain.on('usageStats:clear', () => usageStats.clearAll())

  ipcMain.handle('history:search', (_e, query) => history.search(query))
  ipcMain.on('history:clear', () => history.clearAll())
  ipcMain.handle('history:getEntries', (_e, query) => history.getHistoryList(query))
  ipcMain.handle('history:deleteEntry', (_e, url) => history.deleteEntry(url))
  ipcMain.handle('history:deleteEntriesForHost', (_e, hostname) => {
    const historyDeleted = history.deleteEntriesForHost(hostname)
    const statsDeleted = usageStats.deleteHostname(hostname)
    return historyDeleted || statsDeleted
  })

  ipcMain.handle('activityLog:getEntries', () => activityLog.getRecent(500))
  ipcMain.on('activityLog:clear', () => activityLog.clearAll())

  ipcMain.handle('productivityNudge:getState', () => store.get('productivityNudge'))
  ipcMain.on('productivityNudge:dismiss', () => {
    const cleared = { message: null, timestamp: null }
    store.update('productivityNudge', cleared)
    dashboardWin?.webContents.send('productivityNudge:state', cleared)
  })

  // Grows/shrinks the sender's own chrome strip to fit the address bar's
  // autocomplete dropdown — see setChromeHeight() in tabManager.js for why.
  ipcMain.on('chrome:setHeight', (e, px) => contextForSender(e.sender)?.tabManager.setChromeHeight(px))

  ipcMain.handle('toolbarVisibility:getState', () => store.get('toolbarVisibility'))
  ipcMain.on('toolbarVisibility:setVisible', (_e, { key, visible }) => {
    const state = store.update('toolbarVisibility', { [key]: !!visible })
    broadcastToAllChrome('toolbarVisibility:state', state)
    settingsWin?.webContents.send('toolbarVisibility:state', state)
  })

  ipcMain.handle('aiChat:getState', () => store.get('aiChat'))
  ipcMain.on('aiChat:updateSettings', (_e, patch) => {
    const state = store.update('aiChat', patch)
    settingsWin?.webContents.send('aiChat:state', state)
    aiSidebarView?.webContents.send('aiChat:state', state)
  })
  ipcMain.on('aiChat:toggleSidebar', () => {
    const next = !store.get('aiChat').sidebarVisible
    const state = store.update('aiChat', { sidebarVisible: next })
    tabManager.setRightSidebarVisible(next)
    chromeView?.webContents.send('aiChat:state', state)
  })
  ipcMain.on('aiChat:setSidebarWidth', (_e, px) => {
    // Reusing workspace.js's clamp constants on purpose — same 220-600px
    // range makes sense for either sidebar, no reason to duplicate it.
    const clamped = Math.min(MAX_SIDEBAR_WIDTH, Math.max(MIN_SIDEBAR_WIDTH, Math.round(Number(px)) || store.get('aiChat').sidebarWidth))
    const state = store.update('aiChat', { sidebarWidth: clamped })
    tabManager.setRightSidebarWidth(clamped)
    aiSidebarView?.webContents.send('aiChat:state', state)
  })

  // The renderer owns and sends back its own provider-shaped conversation
  // array each turn (see src/aiChat/aiChat.js) — simpler than mirroring
  // conversation state in the main process too, and it's already exactly
  // what's rendered on screen.
  ipcMain.handle('aiChat:sendMessage', async (_e, { history: convo, userText }) => {
    try {
      const result = await aiChat.runTurn({ history: convo, userText })
      return { ok: true, ...result }
    } catch (err) {
      return { ok: false, error: err.message }
    }
  })

  // Fire-and-forget: unlike aiChat:sendMessage this resolves immediately
  // with just a jobId. The macro itself keeps running in the background —
  // that's the whole point (stay in deep work, don't babysit the chat) —
  // and streams progress back over aiChat:macroEvent/aiChat:macroDone.
  ipcMain.handle('aiChat:runMacro', (_e, { history: convo, userText }) => {
    const jobId = crypto.randomUUID()
    const job = { cancelled: false }
    activeMacroJobs.set(jobId, job)

    aiChat
      .runMacro({
        history: convo,
        userText,
        isCancelled: () => job.cancelled,
        onEvent: (event) => aiSidebarView?.webContents.send('aiChat:macroEvent', { jobId, event })
      })
      .then((result) => {
        aiSidebarView?.webContents.send('aiChat:macroDone', { jobId, ok: true, messages: result.messages })
        new Notification({
          title: 'FocusCompanion',
          body: 'Background task finished — check the AI sidebar for details.',
          timeoutType: 'never'
        }).show()
      })
      .catch((err) => {
        aiSidebarView?.webContents.send('aiChat:macroDone', { jobId, ok: false, error: err.message })
        new Notification({ title: 'FocusCompanion', body: `Background task failed: ${err.message}`, timeoutType: 'never' }).show()
      })
      .finally(() => activeMacroJobs.delete(jobId))

    return { jobId }
  })
  ipcMain.on('aiChat:cancelMacro', (_e, jobId) => {
    const job = activeMacroJobs.get(jobId)
    if (job) job.cancelled = true
  })

  ipcMain.handle('bookmarks:getState', () => store.get('bookmarks'))
  ipcMain.on('bookmarks:add', (_e, bookmark) => {
    const bookmarks = store.get('bookmarks') || { list: [] }
    if (!bookmarks.list.some(b => b.url === bookmark.url)) {
      bookmarks.list.push({ ...bookmark, id: require('crypto').randomUUID(), savedAt: Date.now() })
      store.update('bookmarks', { list: bookmarks.list })
      writeBookmarksJs(bookmarks.list)
      tabManager.broadcastState()
      settingsWin?.webContents.send('bookmarks:state', bookmarks)
    }
  })
  ipcMain.on('bookmarks:remove', (_e, url) => {
    const bookmarks = store.get('bookmarks') || { list: [] }
    const filtered = bookmarks.list.filter(b => b.url !== url)
    store.update('bookmarks', { list: filtered })
    writeBookmarksJs(filtered)
    tabManager.broadcastState()
    settingsWin?.webContents.send('bookmarks:state', { list: filtered })
  })

  ipcMain.handle('focusStats:getState', () => store.get('focusStats'))
  ipcMain.on('focusStats:clear', () => {
    const stats = { pomodorosCompleted: 0, distractionsBlocked: 0, history: {} }
    store.update('focusStats', stats)
    dashboardWin?.webContents.send('focusStats:state', stats)
  })
}

function incrementPomodoroStat() {
  const today = new Date().toLocaleDateString('en-CA')
  const stats = store.get('focusStats') || { pomodorosCompleted: 0, distractionsBlocked: 0, history: {} }
  stats.pomodorosCompleted = (stats.pomodorosCompleted || 0) + 1
  
  if (!stats.history) stats.history = {}
  if (!stats.history[today]) stats.history[today] = { pomodoros: 0, blocked: 0 }
  stats.history[today].pomodoros = (stats.history[today].pomodoros || 0) + 1
  
  store.update('focusStats', stats)
  dashboardWin?.webContents.send('focusStats:state', stats)
}

function incrementBlockedStat() {
  const today = new Date().toLocaleDateString('en-CA')
  const stats = store.get('focusStats') || { pomodorosCompleted: 0, distractionsBlocked: 0, history: {} }
  stats.distractionsBlocked = (stats.distractionsBlocked || 0) + 1
  
  if (!stats.history) stats.history = {}
  if (!stats.history[today]) stats.history[today] = { pomodoros: 0, blocked: 0 }
  stats.history[today].blocked = (stats.history[today].blocked || 0) + 1
  
  store.update('focusStats', stats)
  dashboardWin?.webContents.send('focusStats:state', stats)
}

// Windows taskbar/notification identity — same id as package.json's
// build.appId, so a packaged install and a dev run (electron .) group and
// label themselves consistently instead of falling back to Electron's own
// generic identity. Note: this does NOT change the icon/name an *unpackaged*
// dev run shows in the taskbar itself — that's the literal electron.exe
// binary's own embedded resources, which only a real packaged build
// (`npm run dist`) replaces with this app's own icon.ico/productName.
if (process.platform === 'win32') {
  app.setAppUserModelId('com.focusbrowser.app')
}

app.whenReady().then(() => {
  const bookmarks = store.get('bookmarks') || { list: [] }
  writeBookmarksJs(bookmarks.list || [])

  // Write the initial theme file before any newtab/blocked page can load, and
  // fan out on every subsequent change (including OS light/dark flips while in
  // 'system' mode — see Theme's nativeTheme listener).
  writeThemeJs(theme.getResolved())
  theme.onChange = (resolved) => applyThemeEverywhere(resolved)

  registerUnlockProtocol()
  downloadsManager.registerSession(session.defaultSession)
  downloadsManager.registerIpcHandlers()
  passwordsManager.registerIpcHandlers(() => settingsWin)
  registerBookmarksIoHandlers(ipcMain, store, tabManager, writeBookmarksJs, () => settingsWin)
  privacyManager.registerSession(session.defaultSession)
  privacyManager.registerIpcHandlers(() => settingsWin)
  searchManager.registerIpcHandlers(() => settingsWin)
  blocker.install(session.defaultSession) // must be installed before any tab loads — applies session-wide, covers every window automatically

  blocker.onChange = () => {
    settingsWin?.webContents.send('blocker:state', blocker.state)
  }
  blocker.onBlock = (hostname) => {
    incrementBlockedStat()
  }
  pomodoro.onChange = (state) => {
    broadcastToAllChrome('pomodoro:state', state)
    pomodoroWin?.webContents.send('pomodoro:state', state)
    settingsWin?.webContents.send('pomodoro:state', state)
    updateTray()
  }
  pomodoro.onPhaseBegin = (phase) => {
    if (phase === 'work') {
      workSessionStartAt = Date.now()
      if (pomodoro.settings.autoFocus) applyAutoFocus()
    }
  }
  pomodoro.onPhaseEnd = (phase) => {
    if (phase === 'work') {
      workSessionStartAt = null
      revertAutoFocus()
      incrementPomodoroStat()
    }
  }
  focusMode.onChange = (state) => {
    broadcastToAllChrome('focusMode:state', state)
    settingsWin?.webContents.send('focusMode:state', state)
  }
  workspace.onChange = (state) => {
    workspaceView?.webContents.send('workspace:state', state)
  }
  // Only the Settings window needs live profile updates — the launcher menu
  // is native and built fresh from profiles.state on every open, so chrome
  // has nothing to listen for here.
  profiles.onChange = (state) => {
    settingsWin?.webContents.send('profiles:state', state)
  }
  profiles.onLaunchError = (profileName, command, message) => {
    broadcastToAllChrome('toast:show', `"${profileName}" — command failed: ${command} (${message})`)
  }

  createWindow()
  setupTray()

  // First-run onboarding — auto-show once, never again (unless re-triggered
  // from Settings → "Show welcome tour").
  if (!onboarding.isCompleted()) openOnboardingWindow()
})

app.on('before-quit', () => {
  app.isQuiting = true
  usageStats.stopTracking() // flush whatever's accrued in the current session before exit
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow()
})
